-- =============================================================================
-- 0008_invoices.sql  —  Invoices (line items, status, downloadable PDF)
-- =============================================================================
--
-- ⚠️  REVIEW BEFORE RUNNING. DO NOT APPLY AUTOMATICALLY. ⚠️
--
-- A formal invoice for a lead: one or more line items, a total, a status, an
-- optional due date. Created from the admin (manually or by telling the AI),
-- downloadable as a PDF by admin and client. Distinct from quick PayPal payment
-- requests (the payments table) — invoices are itemized records.
--
-- invoice_no is an auto-incrementing human-friendly number.
-- RLS on, no anon/authenticated policies — server-only (service-role bypasses).
--
-- HOW TO RUN (after review):
--   Supabase SQL editor → paste & run, OR  supabase db push  (CLI). Test first.
-- =============================================================================

create table if not exists public.invoices (
  id          uuid primary key default gen_random_uuid(),
  invoice_no  bigint generated by default as identity,
  lead_id     uuid references public.leads(id) on delete set null,
  items       jsonb not null default '[]'::jsonb,   -- [{ description, amount }]
  total       numeric not null default 0,
  currency    text not null default 'usd',
  status      text not null default 'draft' check (status in ('draft', 'sent', 'paid', 'void')),
  notes       text,
  due_date    timestamptz,
  created_at  timestamptz not null default now(),
  paid_at     timestamptz
);

create index if not exists idx_invoices_lead on public.invoices (lead_id);
create index if not exists idx_invoices_status on public.invoices (status);

alter table public.invoices enable row level security;
-- No anon/authenticated policies: server-only (service-role bypasses RLS).
